version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dockerFile.yml
    ports:
      - "4000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27018
      - DBNAME=ecommerce

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
