import Header from "@/components/Header";
import Footer from "@/components/subcomponents/Footer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="flex flex-col justify-center items-center min-h-screen overflow-y-auto">
        <Header />

        <main className="flex-grow flex items-center justify-center">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
